---
title: "p8105_hw1_LC4052"
author: "Linqi Chu"
output: html_document
date: "2025-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(moderndive)
library(tidyverse)

```

## Problem 1

1. Load the dataset.

```{r}
data("early_january_weather")

```

2. Describe the data.

```{r}
# Names and values of important variables
str(early_january_weather)
early_january_weather = janitor::clean_names(early_january_weather)
names(early_january_weather)

```
```{r}
# size of the dataset
nrow(early_january_weather)
ncol(early_january_weather)

```

```{r}
mean_tmp = mean(early_january_weather$temp)
mean_tmp

```
The variables in this dataset include "origin", "year", "month", "day", "hour", "temp", "dewp", "humid", "wind_dir" ,"wind_speed", "wind_gust", "precip", "pressure"   "visib",and "time_hour".

The dataset has 358 rows and 15 columns. The mean temperature is 39.58212.


```{r}


```


```{r}

```


## Problem 2

```{r}




```


```{r}
mean

as.numeric


# please show this chunk but not the output



```


